"""Schema Cuidum 102 entidades (generado desde src.models.CallEntities).

NO editar a mano: regenerar con scripts/generate_schema_102.py
"""
from core.schema import FieldSpec, build_dynamic_model

FIELDS_102: list[FieldSpec] = [
    FieldSpec(name='problema_reportado', type='string', description="Motivo principal o problema que originó la llamada. Ej: 'La cuidadora llegó tarde', 'Problema con la factura', 'Quiero cambiar de cuidadora'", ),
    FieldSpec(name='urgencia', type='string', description='Nivel de urgencia de la llamada.', ),
    FieldSpec(name='resolucion', type='string', description="Cómo se resolvió o quedó la llamada. Ej: 'Se envía email con presupuesto', 'Queda en llamar más tarde', 'Se programa visita'", ),
    FieldSpec(name='temas_clave', type='list', description="Lista de temas clave tratados en la llamada. Ej: ['renovación', 'horarios', 'pago', 'sustitución']", ),
    FieldSpec(name='menciona_baja', type='bool', description='True si el interlocutor menciona explícitamente la posibilidad de darse de baja o cancelar el servicio.', ),
    FieldSpec(name='menciona_queja', type='bool', description='True si hay una queja explícita sobre el servicio, la cuidadora, la facturación o cualquier aspecto.', ),
    FieldSpec(name='necesidad_especifica', type='string', description="Necesidad concreta expresada. Ej: 'Necesito alguien que hable inglés', 'Solo por las mañanas', 'Necesito factura con CIF'", ),
    FieldSpec(name='quien_llama', type='string', description="Persona que realiza la llamada: 'familiar', 'paciente', 'cuidadora', 'tutor_legal', 'otro'.", ),
    FieldSpec(name='relacion_llamante_paciente', type='string', description="Relación del llamante con el paciente. Ej: 'hijo/a', 'cónyuge', 'hermano/a', 'ella_misma', 'cuidadora_contratada'.", ),
    FieldSpec(name='ubicacion_servicio', type='string', description="Ubicación donde se presta el servicio. Ej: 'domicilio_paciente', 'residencia', 'hospital', 'domicilio_familiar'.", ),
    FieldSpec(name='tipo_vivienda_acceso', type='string', description="Tipo de vivienda y condiciones de acceso. Ej: 'piso_con_ascensor', 'casa_sin_ascensor', 'piso_sin_ascensor_4°', 'residencia'.", ),
    FieldSpec(name='convivencia_paciente', type='string', description="Con quién convive el paciente. Ej: 'solo', 'con_conyuge', 'con_hijos', 'con_cuidadora_interna', 'residencia'.", ),
    FieldSpec(name='personas_en_casa', type='string', description="Personas presentes en el domicilio durante el servicio. Ej: 'solo_el_paciente', 'familiar_presente', 'hay_otra_cuidadora', 'hay_ninos'.", ),
    FieldSpec(name='tipo_servicio_actual', type='string', description="Tipo de servicio contratado actualmente. Ej: 'compania', 'aseo_personal', 'cuidados_enfermeria', 'acompanamiento_medico', 'limpieza', 'mixto'.", ),
    FieldSpec(name='antiguedad_estimada', type='string', description="Antigüedad aproximada del cliente con el servicio. Ej: 'nuevo_menos_1_mes', '1_3_meses', '3_6_meses', '6_12_meses', 'mas_de_1_ano'.", ),
    FieldSpec(name='num_cuidadoras_historico_inferido', type='string', description="Número de cuidadoras distintas que ha tenido el cliente según se infiere de la conversación. Ej: 'una_sola', 'dos_tres', 'muchas_rotacion', 'no_menciona'.", ),
    FieldSpec(name='frecuencia_contacto_inferida', type='string', description="Frecuencia con la que el cliente contacta con la empresa. Ej: 'primera_llamada', 'contacto_habitual', 'contacto_frecuente_quejas', 'no_se_infiere'.", ),
    FieldSpec(name='patologia_principal', type='string', description='Patología principal del paciente mencionada. Ej: \'Alzheimer\', \'Parkinson\', \'ictus\', \'diabetes\', "fractura_cadera", "vejez_debilidad".', ),
    FieldSpec(name='patologia_severidad', type='string', description="Severidad estimada de la patología principal. Ej: 'leve', 'moderada', 'avanzada', 'estadio_terminal', 'no_mencionada'.", ),
    FieldSpec(name='patologias_secundarias', type='list', description="Lista de patologías secundarias o comorbilidades del paciente. Ej: ['hipertensión', 'diabetes tipo 2', 'artrosis'].", ),
    FieldSpec(name='evolucion_reciente_salud', type='string', description="Evolución reciente del estado de salud. Ej: 'estable', 'mejorando', 'empeorando', 'post_operatorio', 'reciente_diagnostico'.", ),
    FieldSpec(name='movilidad_actual', type='string', description='Nivel de movilidad actual del paciente. Ej: \'independiente\', \'baston_andador\', \'silla_ruedas\', "encamado", "dependencia_total".', ),
    FieldSpec(name='continencia', type='string', description="Estado de continencia del paciente. Ej: 'continente', 'incontinencia_urinaria', 'incontinencia_fecal', 'doble_incontinencia', 'no_mencionada'.", ),
    FieldSpec(name='alimentacion', type='string', description="Necesidades o estado de alimentación del paciente. Ej: 'independiente', 'asistida_parcial', 'sonda_enteral', 'alimentacion_triturada', 'dificultad_deglucion'.", ),
    FieldSpec(name='estado_cognitivo', type='string', description="Estado cognitivo del paciente. Ej: 'orientado', 'desorientacion_parcial', 'desorientacion_grave', 'demencia_avanzada', 'no_mencionado'.", ),
    FieldSpec(name='estado_animo_paciente', type='string', description="Estado anímico del paciente según lo descrito. Ej: 'animado', 'depresivo', 'apatia', 'ansioso', 'irritable', 'no_mencionado'.", ),
    FieldSpec(name='historial_caidas', type='string', description="Historial de caídas del paciente. Ej: 'caidas_frecuentes', 'caida_reciente', 'sin_caidas', 'riesgo_caidas_mencionado', 'no_mencionado'.", ),
    FieldSpec(name='hospitalizaciones_recientes', type='string', description='Hospitalizaciones recientes del paciente. Ej: \'hospitalizado_ultimo_mes\', \'alta_reciente\', "ingreso_programado", "sin_hospitalizaciones", \'no_mencionado\'.', ),
    FieldSpec(name='medicacion_complejidad', type='string', description="Complejidad de la medicación del paciente. Ej: 'simple_pocos_farmacos', 'compleja_multiples', 'cambio_reciente_medicacion', 'inyectable', 'no_mencionada'.", ),
    FieldSpec(name='necesita_rehabilitacion', type='bool', description='True si el paciente necesita o está recibiendo rehabilitación (fisioterapia, logopedia, etc.).', ),
    FieldSpec(name='calidad_suenio', type='string', description="Calidad del sueño del paciente. Ej: 'buena', 'regular_insomnio', 'despertares_nocturnos', 'somnilencia_diurna', 'no_mencionada'.", ),
    FieldSpec(name='apetito_nutricion', type='string', description="Estado del apetito y nutrición del paciente. Ej: 'normal', 'poco_apetito', 'perdida_peso', 'hidratacion_insuficiente', 'no_mencionado'.", ),
    FieldSpec(name='dolor_cronico', type='string', description="Presencia y descripción del dolor crónico. Ej: 'dolor_leve_controlado', 'dolor_moderado_persistente', 'dolor_severo_no_controlado', 'no_mencionado'.", ),
    FieldSpec(name='riesgo_ulceras', type='bool', description='True si hay riesgo mencionado de úlceras por presión o el paciente ya las tiene.', ),
    FieldSpec(name='alergias_intolerancias', type='list', description="Lista de alergias o intolerancias del paciente. Ej: ['lactosa', 'gluten', 'alergia_medicamentosa'].", ),
    FieldSpec(name='necesidades_no_cubiertas', type='list', description="Necesidades de salud que el cliente menciona que no están siendo cubiertas. Ej: ['falta_fisioterapia', 'necesita_enfermera', 'necesita_logopeda'].", ),
    FieldSpec(name='derivacion_medica', type='string', description="Derivación médica mencionada o necesaria. Ej: 'pendiente_valoracion_neurologo', 'derivado_a_urgencias', 'pendiente_cita_medico', 'no_mencionada'.", ),
    FieldSpec(name='situacion_pagos', type='string', description="Situación de los pagos del cliente. Ej: 'al_dia', 'pendiente_ultimo_mes', 'adeuda_varios_meses', 'problemas_pago_recurrentes', 'no_mencionada'.", ),
    FieldSpec(name='metodo_pago', type='string', description="Método de pago usado o preferido. Ej: 'transferencia', 'tarjeta', 'domiciliacion', 'efectivo', 'bizum', 'no_mencionado'.", ),
    FieldSpec(name='queja_precio_intensidad', type='string', description="Intensidad de la queja sobre el precio o relación calidad-precio. Ej: 'sin_queja', 'leve_mencion_caro', 'queja_explicita', 'amenaza_baja_por_precio', 'renegociacion_exitosa'.", ),
    FieldSpec(name='negociacion_tarifa', type='bool', description='True si el cliente solicita explícitamente negociar la tarifa o pide un descuento.', ),
    FieldSpec(name='pension_ingresos_mencionados', type='string', description="Mención de pensión, ingresos o situación económica. Ej: 'pension_no_contributiva', 'pension_contributiva_baja', 'ingresos_familiares_medios', 'dificultad_economica', 'no_mencionado'.", ),
    FieldSpec(name='subvenciones', type='string', description="Subvenciones o ayudas mencionadas. Ej: 'ley_dependencia', 'ayuda_municipal', 'seguro_privado', 'no_mencionada'.", ),
    FieldSpec(name='ampliacion_horas_interes', type='bool', description='True si el cliente muestra interés en ampliar las horas del servicio (upsell opportunity).', ),
    FieldSpec(name='reduccion_horas_riesgo', type='bool', description='True si el cliente sugiere o amenaza con reducir horas del servicio (downgrade risk).', ),
    FieldSpec(name='servicios_extra_solicitados', type='list', description="Lista de servicios adicionales solicitados por el cliente. Ej: ['fisioterapia', 'compania_nocturna', 'cuidados_enfermeria', 'limpieza_profunda'].", ),
    FieldSpec(name='tipo_contrato', type='string', description="Tipo de contrato del cliente. Ej: 'particular', 'seguro_privado', 'servicio_publico', 'mutualidad', 'no_mencionado'.", ),
    FieldSpec(name='confianza_economica', type='string', description="Confianza del cliente en la gestión económica. Ej: 'confianza_total', 'dudas_facturas', 'reclamacion_factura', 'desconfianza_explicita', 'no_mencionada'.", ),
    FieldSpec(name='intencion_permanencia', type='string', description="Intención del cliente de permanecer en el servicio desde perspectiva económica. Ej: 'seguro_permanece', 'dudas_economicas', 'probable_baja_por_precio', 'buscando_alternativas', 'no_se_infiere'.", ),
    FieldSpec(name='vinculo_cuidadora_paciente', type='string', description="Vínculo entre la cuidadora actual y el paciente. Ej: 'excelente_afecto', 'bueno_profesional', 'tenso_conflictivo', 'indiferente', 'no_mencionado'.", ),
    FieldSpec(name='vinculo_cuidadora_familia', type='string', description="Vínculo entre la cuidadora y la familia. Ej: 'muy_buena_relacion', 'relacion_distante', 'conflicto_explicito', 'no_mencionado'.", ),
    FieldSpec(name='satisfaccion_general', type='float', description='Satisfacción general del cliente valorada de 0 a 10. Ej: 8.5 para muy satisfecho, 2.0 para muy insatisfecho.', ),
    FieldSpec(name='sentimiento_apertura', type='string', description="Sentimiento o emoción predominante al inicio de la llamada. Ej: 'cordial', 'neutro', 'tenso', 'frustrado', 'urgente', 'agradecido'.", ),
    FieldSpec(name='sentimiento_cierre', type='string', description="Sentimiento o emoción predominante al final de la llamada. Ej: 'satisfecho', 'aliviado', 'aun_frustrado', 'indiferente', 'agradecido', 'molesto'.", ),
    FieldSpec(name='tendencia_emocional_llamada', type='string', description="Evolución emocional durante la llamada. Ej: 'mejora_tras_gestion', 'empeora_por_respuesta', 'se_mantiene_positiva', 'se_mantiene_negativa', 'volatil_cambios_bruscos'.", ),
    FieldSpec(name='estres_cuidador_familiar', type='string', description="Nivel de estrés del cuidador familiar. Ej: 'sin_estres_aparente', 'estres_moderado', 'estres_alto_agotamiento', 'sindrome_cuidador', 'no_aplica'.", ),
    FieldSpec(name='apoyo_familiar', type='string', description="Nivel de apoyo familiar en el cuidado. Ej: 'familia_implicada', 'apoyo_parcial', 'sin_apoyo_familiar', 'conflicto_familiar_cuidado', 'no_mencionado'.", ),
    FieldSpec(name='conflictos_familiares', type='string', description='Conflictos familiares mencionados relacionados con el cuidado. Ej: \'desacuerdo_horarios\', \'disputa_economica\', "desacuerdo_tratamiento", "sin_conflictos", \'no_mencionados\'.', ),
    FieldSpec(name='confianza_empresa', type='string', description="Confianza del cliente en la empresa. Ej: 'alta', 'media', 'baja_desconfianza', 'traicionada_por_incidente', 'no_mencionada'.", ),
    FieldSpec(name='lealtad_marca', type='string', description="Nivel de lealtad del cliente hacia la marca. Ej: 'defensor_promotor', 'cliente_fiel_pasivo', 'cliente_riesgo_cambio', 'busca_activamente_alternativas', 'no_se_infiere'.", ),
    FieldSpec(name='menciona_competidores', type='list', description="Lista de competidores mencionados por el cliente. Ej: ['Atenzia', 'Sanyres', 'Clece', 'Mimo'].", ),
    FieldSpec(name='probabilidad_recomendacion', type='string', description="Probabilidad inferida de que el cliente recomiende el servicio. Ej: 'alta', 'media', 'baja', 'no_se_infiere'.", ),
    FieldSpec(name='frustracion_acumulada', type='string', description="Nivel de frustración acumulada del cliente. Ej: 'sin_frustracion', 'leve_incidencias_puntuales', 'frustracion_acumulada_visible', 'cliente_al_limite_explosion'.", ),
    FieldSpec(name='evento_vital', type='string', description='Evento vital significativo mencionado. Ej: \'fallecimiento_conyuge\', \'nacimiento_nieto\', "cambio_domicilio", "ingreso_residencia", \'empeoramiento_diagnostico\', \'ninguno_mencionado\'.', ),
    FieldSpec(name='soledad_aislamiento', type='bool', description='True si se menciona sentimiento de soledad o aislamiento social del paciente o familiar.', ),
    FieldSpec(name='agradecimiento_cliente', type='bool', description='True si el cliente expresa agradecimiento explícito hacia la empresa, gestor o cuidadora.', ),
    FieldSpec(name='empatia_gestor', type='bool', description='True si el gestor muestra empatía explícita durante la llamada (validar sentimientos, disculparse, mostrar comprensión).', ),
    FieldSpec(name='cambios_horario_frecuencia', type='string', description="Frecuencia de cambios de horario solicitados. Ej: 'sin_cambios', 'cambio_puntual', 'cambios_recurrentes', 'reprogramacion_constante'.", ),
    FieldSpec(name='cancelaciones_ratio_sugerido', type='string', description="Ratio de cancelaciones sugerido por el discurso. Ej: 'nunca_cancela', 'cancela_ocasionalmente', 'cancela_a_menudo', 'no_se_infiere'.", ),
    FieldSpec(name='solicitudes_ultima_hora', type='bool', description='True si el cliente hace solicitudes de última hora que afectan la planificación.', ),
    FieldSpec(name='problemas_transporte', type='string', description='Problemas de transporte de la cuidadora para llegar al domicilio. Ej: \'acceso_transporte_publico\', \'dificultad_aparcamiento\', "lejania_domicilio", "sin_problemas", "no_mencionados".', ),
    FieldSpec(name='problemas_acceso_vivienda', type='string', description="Problemas de acceso a la vivienda. Ej: 'portero_automatico', 'escaleras_sin_ascensor', 'llaves_no_disponibles', 'mascota_suelta', 'sin_problemas'.", ),
    FieldSpec(name='mascotas_en_domicilio', type='string', description='Presencia de mascotas en el domicilio. Ej: \'perro\', \'gato\', \'varias_mascotas\', "sin_mascotas", "no_mencionado".', ),
    FieldSpec(name='incidencias_repetitivas', type='list', description="Lista de incidencias que se repiten en el servicio. Ej: ['retrasos_frecuentes', 'faltas_aviso', 'material_no_entregado', 'horario_no_respetado'].", ),
    FieldSpec(name='rotacion_cuidadoras_explicita', type='string', description="Mención explícita de rotación de cuidadoras. Ej: 'misma_siempre', 'rotacion_normal', 'mucha_rotacion_queja', 'ha_cambiado_varias_veces', 'no_mencionada'.", ),
    FieldSpec(name='disponibilidad_real_horaria', type='string', description="Disponibilidad horaria real del cliente o paciente. Ej: 'horario_fijo_manana', 'horario_fijo_tarde', 'horario_variable', 'disponibilidad_total', 'no_mencionada'.", ),
    FieldSpec(name='necesidad_festivos', type='string', description="Necesidad de cobertura en festivos o fines de semana. Ej: 'necesita_festivos_si', 'no_necesita_festivos', 'necesita_fines_semana', 'duda_sobre_festivos', 'no_mencionada'.", ),
    FieldSpec(name='barreras_logisticas', type='list', description="Lista de barreras logísticas generales. Ej: ['zona_mala_conexion', 'no_coche_cuidadora', 'zona_inundacion', 'carretera_complicada_invierno'].", ),
    FieldSpec(name='problemas_material_equipamiento', type='list', description="Lista de problemas con material o equipamiento. Ej: ['falta_panales', 'cama_articulada_no_disponible', 'silla_ruedas_rota', 'falta_material_cura'].", ),
    FieldSpec(name='canal_comunicacion', type='string', description="Canal por el que se recibe la llamada. Ej: 'telefono_entrante', 'telefono_saliente', 'email_derivado', 'whatsapp_derivado', 'no_mencionado'.", ),
    FieldSpec(name='duracion_llamada_minutos', type='float', description='Duración estimada de la llamada en minutos.', ),
    FieldSpec(name='claridad_comunicacion', type='string', description="Claridad con la que el interlocutor se expresa. Ej: 'clara_fluida', 'algo_confusa_vaguedad', 'muy_confusa_contradicciones', 'no_se_infiere'.", ),
    FieldSpec(name='nivel_exigencia', type='string', description='Nivel de exigencia del cliente durante la llamada. Ej: \'bajo\', \'moderado_razonable\', \'alto_exigente\', "muy_alto_irrazonable", "no_se_infiere".', ),
    FieldSpec(name='actitud_cliente', type='string', description="Actitud general del cliente en la llamada. Ej: 'colaborativa', 'pasiva', 'exigente', 'hostil', 'agradecida', 'desconfiada', 'indiferente'.", ),
    FieldSpec(name='coherencia_relato', type='string', description="Coherencia del relato del cliente. Ej: 'coherente', 'parcialmente_contradictorio', 'contradicciones_importantes', 'no_se_infiere'.", ),
    FieldSpec(name='receptividad_gestion', type='string', description="Receptividad del cliente a las soluciones propuestas por el gestor. Ej: 'acepta_de_inmediato', 'acepta_tras_dudas', 'rechaza_alternativas', 'no_se_propone_gestion', 'no_se_infiere'.", ),
    FieldSpec(name='urgencia_voz_tono', type='string', description="Urgencia percibida en el tono de voz del interlocutor. Ej: 'tono_tranquilo', 'tono_preocupado', 'tono_angustiado', 'tono_agresivo', 'tono_llanto', 'no_se_infiere'.", ),
    FieldSpec(name='churn_risk_score', type='float', description='Riesgo de churn general estimado de 0 a 1. 0 = mínimo riesgo, 1 = abandono inminente.', ),
    FieldSpec(name='baja_probabilidad_inferida', type='float', description='Probabilidad inferida de baja del servicio de 0 a 1.', ),
    FieldSpec(name='menciona_competidores_lista', type='list', description="Lista de competidores que el cliente menciona haber contactado o estar considerando. Ej: ['Atenzia', 'Clece'].", ),
    FieldSpec(name='frustracion_acumulada_tendencia', type='string', description="Tendencia de la frustración acumulada en el tiempo. Ej: 'estable_baja', 'en_aumento_preocupante', 'estallido_reciente', 'en_descenso_mejoria', 'no_se_infiere'.", ),
    FieldSpec(name='deseo_cambio_cuidadora', type='bool', description='True si el cliente expresa deseo explícito de cambiar de cuidadora.', ),
    FieldSpec(name='umbral_paciencia_cliente', type='string', description="Estado del umbral de paciencia del cliente. Ej: 'paciente_tolerante', 'paciencia_gastandose', 'al_limite_ultima_oportunidad', 'sin_paciencia_actuara', 'no_se_infiere'.", ),
    FieldSpec(name='fase_ciclo_cliente_inferida', type='string', description="Fase del ciclo de vida del cliente inferida. Ej: 'onboarding', 'estable', 'riesgo_baja', 'recuperacion_tras_incidencia', 'salida_programada', 'no_se_infiere'.", ),
    FieldSpec(name='downgrade_risk', type='bool', description='True si hay indicios de que el cliente reducirá horas o servicios contratados.', ),
    FieldSpec(name='upsell_opportunity', type='bool', description='True si hay indicios de que el cliente podría ampliar horas o contratar servicios adicionales.', ),
    FieldSpec(name='anomalia_comportamiento', type='bool', description='True si se detecta un comportamiento anómalo respecto al patrón histórico del cliente (nunca llamaba y ahora sí, cambio brusco de tono, etc.).', ),
    FieldSpec(name='mejora_salud_implica_baja', type='bool', description='True si la mejora de salud del paciente implica riesgo de reducción o baja del servicio.', ),
    FieldSpec(name='amenaza_reclamacion_legal', type='bool', description='True si el cliente amenaza con acciones legales, reclamación formal o abogado.', ),
    FieldSpec(name='ventana_abandono_estimada_dias', type='int', description='Estimación en días del plazo probable de abandono del servicio si no se interviene. Null si no aplica.', ),
    FieldSpec(name='proxima_necesidad_predicha', type='string', description='Predicción de la próxima necesidad del cliente. Ej: \'solicitara_aumento_horas\', \'pedira_cambio_cuidadora\', \'reclamara_factura_pendiente\', \'contactara_competencia\', "dara_baja", "no_mantenimiento_sin_cambios".', ),
    FieldSpec(name='discrepancia_datos_odoo', type='list', description="Lista de discrepancias detectadas entre lo que dice el cliente y los datos en Odoo. Ej: ['horario_no_coincide', 'cuidadora_asignada_no_es_actual', 'direccion_diferente', 'tarifa_diferente'].", ),
]

CallEntities102 = build_dynamic_model(FIELDS_102, "CallEntities102")
